### ISSUE TITLE
Database connection configuration

### ISSUE THREAD

**Issue by deleepa** [deleepa/simple-api-server#1]
The database connection is created in database.js. However at the moment it is depending on a config.json file to read the connection configs. This must be modified to read from environment variables, or accept default values. This is generally a better way to manage configurations.

**Comment by raj-subhankar** [comment]
Do you want to get rid of the config file and use constant values directly in the database.js file?

**Comment by Mokanarangan** [comment]
By environment variables do you mean variables to be passed while we run the npm commands..??

**Comment by deleepa** [comment]
@Mokanarangan not really. Environment variables are set using either the `.bashrc` file or `.profile` files on Linux (not sure about Windows). They are initalised and set up when the relevant user logs into the system. Have a look at what @murzeus has done in PR #6.
