### ISSUE TITLE
Create a route to accept DELETE requests

### ISSUE THREAD

**Issue by murzeus** [deleepa/simple-api-server#10]
There should be a route to accept delete requests

**Comment by raj-subhankar** [comment]
route to delete users by email id?

**Comment by murzeus** [comment]
@raj-subhankar yes, we can't use the name here because it can be ambiguous.

**Comment by raj-subhankar** [comment]
okay I am on it

**Comment by raj-subhankar** [comment]
Review #11. Receiving email id as params instead of query. Do let me know if you want it as query. I think using params is cleaner.

**Comment by murzeus** [comment]
@raj-subhankar yes, I agree.
