### ISSUE TITLE
Edit user route

### ISSUE THREAD

**Issue by deleepa** [deleepa/simple-api-server#2]
At the moment there are two routes, GET to get a list of users and POST to add new user. It would be awesome if we could add filtering for the GET route so that user's could be fetched by their email address.

**Comment by murzeus** [comment]
I can help with this

**Comment by deleepa** [comment]
Awesome @murzeus

**Comment by raj-subhankar** [comment]
I am trying too

**Comment by murzeus** [comment]
Since the PR of @raj-subhankar had many issues I thought about writing it myself.
