### ISSUE TITLE
Code comments

### ISSUE THREAD

**Issue by deleepa** [deleepa/simple-api-server#3]
Since this project is for beginners, the code should be very well commented. This aspect of the code must be improved.

**Comment by daviditsygin** [comment]
I can help with this

**Comment by deleepa** [comment]
Sounds good @daviditsygin

**Comment by daviditsygin** [comment]
submitted a PR #4 let me know what you think

**Comment by deleepa** [comment]
Awesome. I've accepted your PR. Thanks!
