### ISSUE TITLE
Add .env file to .gitignore

### ISSUE THREAD

**Issue by dhwanilvyas** [deleepa/simple-api-server#8]
The .env file should be in the .gitignore file. Create an .env.example file if you want to show the user what variables are to be used.

**Comment by deleepa** [comment]
That's actually an awesome recommendation! The code needs to be modified as well to accept default values, if the .env file is not available, I think.

**Comment by dhwanilvyas** [comment]
I can work on it.

**Comment by dhwanilvyas** [comment]
#9

**Comment by murzeus** [comment]
@dhwanilvyas Thanks.
